//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criteria
    {
        public int Id { get; set; }
        public string Goal { get; set; }
        public Nullable<bool> Storage { get; set; }
        public Nullable<bool> Application { get; set; }
        public Nullable<bool> Website { get; set; }
        public Nullable<bool> Mobile { get; set; }
        public int ProjectProjectId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
