//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Criteria()
        {
            this.Storage = false;
            this.Application = false;
            this.Website = false;
            this.Mobile = false;
        }
    
        public int Id { get; set; }
        public string Goal { get; set; }
        public bool Storage { get; set; }
        public bool Application { get; set; }
        public bool Website { get; set; }
        public bool Mobile { get; set; }
    }
}
