
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapstoneProject
{

using System;
    using System.Collections.Generic;
    
public partial class Feedback
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Feedback()
    {

        this.Rating = 0D;

    }


    public int Id { get; set; }

    public string Comment { get; set; }

    public double Rating { get; set; }

    public int ClientUserId { get; set; }



    public virtual Client Client { get; set; }

}

}
