
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapstoneProject
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectTypes
{

    public int Id { get; set; }

    public string Type { get; set; }

    public string Title { get; set; }

    public string IP { get; set; }

    public string ClientInteraction { get; set; }

    public string Pressure { get; set; }

    public string Operation { get; set; }

    public string Benefits { get; set; }

    public string Description { get; set; }

}

}
