
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapstoneProject
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectRanking
{

    public int Id { get; set; }

    public string ProjectId { get; set; }

    public string Rank { get; set; }

    public int GroupGroupId { get; set; }



    public virtual Group Group { get; set; }

}

}
