
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapstoneProject
{

using System;
    using System.Collections.Generic;
    
public partial class Skillset
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Skillset()
    {

        this.CSharp = 0D;

        this.Java = 0D;

        this.Database = 0D;

        this.WebDev = 0D;

        this.MobileDev = 0D;

        this.ApplDev = 0D;

        this.UIDesign = 0D;

    }


    public int Id { get; set; }

    public double CSharp { get; set; }

    public double Java { get; set; }

    public double Database { get; set; }

    public double WebDev { get; set; }

    public double MobileDev { get; set; }

    public double ApplDev { get; set; }

    public double UIDesign { get; set; }



    public virtual Group Group { get; set; }

    public virtual Student Student { get; set; }

}

}
