//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Skillset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skillset()
        {
            this.Programming = 0D;
            this.WebDev = 0D;
            this.MobileDev = 0D;
            this.ApplDev = 0D;
            this.UIDesign = 0D;
        }
        public int Id { get; set; }
        [Range(0, 10)]
        [DisplayFormat(DataFormatString = "{0:n1}")]
        [Display(Name = "Programming")]
        public double Programming { get; set; }
        [Range(0, 10)]
        [DisplayFormat(DataFormatString = "{0:n1}")]
        [Display(Name = "Web Development")]
        public double WebDev { get; set; }
        [Range(0, 10)]
        [DisplayFormat(DataFormatString = "{0:n1}")]
        [Display(Name = "Mobile Development")]
        public double MobileDev { get; set; }
        [Range(0, 10)]
        [DisplayFormat(DataFormatString = "{0:n1}")]
        [Display(Name = "Application Development")]
        public double ApplDev { get; set; }
        [Range(0, 10)]
        [DisplayFormat(DataFormatString = "{0:n1}")]
        [Display(Name = "UI Designing")]
        public double UIDesign { get; set; }

        public virtual Student Student { get; set; }
        public virtual Group Group { get; set; }
    }
}
