
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapstoneProject
{

using System;
    using System.Collections.Generic;
    
public partial class Student : User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Student()
    {

        this.Coops = new HashSet<Coop>();

    }


    public int StudentId { get; set; }

    public int StudentNumber { get; set; }

    public string Interests { get; set; }

    public int ProgramId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Coop> Coops { get; set; }

    public virtual Group Group { get; set; }

    public virtual Skillset Skillset { get; set; }

}

}
